# Generated by Django 5.2 on 2026-08-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('level', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Information'), ('success', 'Success')], db_index=True, default='info', max_length=10, verbose_name='Тип')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на объект')),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Ключ дедупликации')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Просмотрено')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='Закрыто')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
