# Generated by Django 5.2 on 2026-09-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_import_talent_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveinvite',
            name='candidate',
        ),
        migrations.AddField(
            model_name='reserveinvite',
            name='submissions',
            field=models.PositiveIntegerField(default=0, verbose_name='Заполнений'),
        ),
        migrations.AlterField(
            model_name='reserveinvite',
            name='recipient',
            field=models.CharField(blank=True, help_text='Для кого создана ссылка — чтобы не путать несколько ссылок.', max_length=255, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='reserveinvite',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее заполнение'),
        ),
    ]
