# Generated by Django 5.2 on 2026-09-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_remove_reserveinvite_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveinvite',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Пусто — общая ссылка на анкету; иначе ссылка на правку карточки.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_links', to='reserve.reservecandidate', verbose_name='Кандидат'),
        ),
    ]
