# Generated by Django 5.2 on 2026-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_reserveinvite_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservecandidate',
            options={'ordering': ['-priority', '-rating', 'full_name'], 'verbose_name': 'Кандидат резерва', 'verbose_name_plural': 'Резерв кадров'},
        ),
        migrations.AddField(
            model_name='reservecandidate',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Приоритет в списке'),
        ),
    ]
