# Generated by Django 5.2 on 2026-09-16 15:18

import apps.reserve.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_alter_reservecandidate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Кандидат добавлен'), ('invited', 'Отправлена ссылка на анкету'), ('shared', 'Профиль отправлен по ссылке'), ('submitted', 'Анкета заполнена'), ('updated', 'Данные изменены'), ('status', 'Смена статуса'), ('evaluated', 'Внутренняя оценка'), ('recommended', 'Рекомендация компании'), ('rec_status', 'Результат по рекомендации')], max_length=20, verbose_name='Событие'),
        ),
        migrations.CreateModel(
            name='ReserveShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('token', models.CharField(default=apps.reserve.models.generate_token, max_length=64, unique=True, verbose_name='Токен')),
                ('recipient', models.CharField(blank=True, help_text='Компания или человек, которому отправили профиль.', max_length=255, verbose_name='Для кого')),
                ('show_contacts', models.BooleanField(default=False, verbose_name='Показывать контакты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний просмотр')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='reserve.reservecandidate', verbose_name='Кандидат')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Ссылка на профиль кандидата',
                'verbose_name_plural': 'Ссылки на профили кандидатов',
                'ordering': ['-created_at'],
            },
        ),
    ]
