# Generated by Django 5.2 on 2026-09-16 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_reserve_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservesharelink',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='share_collections', to='reserve.reservecandidate', verbose_name='Кандидаты подборки'),
        ),
        migrations.AlterField(
            model_name='reservesharelink',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Пусто — ссылка на подборку из нескольких кандидатов.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='reserve.reservecandidate', verbose_name='Кандидат'),
        ),
    ]
