# Generated by Django 5.2 on 2026-09-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_reserve_share_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservecandidate',
            name='pool',
            field=models.CharField(choices=[('staff', 'Сотрудники'), ('intern', 'Стажёры')], db_index=True, default='staff', help_text='Стажёров отправляют в резерв тимлиды — они уходят в общую таблицу.', max_length=10, verbose_name='Кто это'),
        ),
    ]
