# Generated by Django 5.2 on 2026-08-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('required_for_delivery', models.BooleanField(default=False, verbose_name='Обязателен для сдачи')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер')),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='Файл')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('awaiting', 'Ожидает подписи'), ('signed', 'Подписан'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Подписан')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Проект')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
