# Generated by Django 5.2

from django.db import migrations


REMOVED_CODES = [
    'annex', 'extra_agreement', 'work_act', 'final_act',
    'access_transfer', 'requisites', 'other',
]


def trim_types(apps, schema_editor):
    DocumentType = apps.get_model('documents', 'DocumentType')
    Document = apps.get_model('documents', 'Document')
    for code in REMOVED_CODES:
        doc_type = DocumentType.objects.filter(code=code).first()
        if doc_type and not Document.objects.filter(doc_type=doc_type).exists():
            doc_type.delete()
    DocumentType.objects.filter(code='acceptance_act').update(
        required_for_delivery=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(trim_types, migrations.RunPython.noop),
    ]
