# Generated by Django 5.2 on 2026-09-16 15:33

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documenttemplate'),
        ('projects', '0015_project_stages_checked_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('about_business', models.TextField(blank=True, verbose_name='О бизнесе')),
                ('goal', models.TextField(blank=True, verbose_name='Цель проекта')),
                ('target_audience', models.TextField(blank=True, verbose_name='Целевая аудитория')),
                ('required_features', models.TextField(blank=True, verbose_name='Обязательный функционал')),
                ('references', models.TextField(blank=True, verbose_name='Референсы')),
                ('deadline_wish', models.CharField(blank=True, max_length=255, verbose_name='Желаемый срок')),
                ('existing_site_url', models.CharField(blank=True, max_length=500, verbose_name='Действующий сайт/приложение')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Домен')),
                ('integrations', models.TextField(blank=True, verbose_name='Нужные интеграции')),
                ('languages', models.CharField(blank=True, max_length=255, verbose_name='Язык(и)')),
                ('content_owner', models.CharField(blank=True, max_length=255, verbose_name='Кто наполняет контентом')),
                ('social_links', models.TextField(blank=True, verbose_name='Соцсети компании')),
                ('competitors', models.TextField(blank=True, verbose_name='Конкуренты')),
                ('brand_materials', models.CharField(blank=True, max_length=500, verbose_name='Бренд-бук/логотип')),
                ('decision_maker', models.CharField(blank=True, max_length=255, verbose_name='Кто принимает решение')),
                ('requirements_file', models.FileField(blank=True, upload_to='project_briefs/%Y/%m/', verbose_name='Готовое ТЗ/документация')),
                ('preferred_contact', models.CharField(blank=True, max_length=255, verbose_name='Удобный способ связи')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Доп. пожелания')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Бриф проекта',
                'verbose_name_plural': 'Брифы проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectBriefLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('token', models.CharField(default=apps.documents.models.generate_brief_token, max_length=64, unique=True, verbose_name='Токен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('submissions', models.PositiveIntegerField(default=0, verbose_name='Заполнений')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее заполнение')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief_links', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Ссылка на бриф',
                'verbose_name_plural': 'Ссылки на бриф',
                'ordering': ['-created_at'],
            },
        ),
    ]
