# Generated by Django 5.2 on 2026-08-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('week_start', models.DateField(unique=True, verbose_name='Начало недели')),
                ('data', models.JSONField(default=dict, verbose_name='Показатели')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий руководителя')),
            ],
            options={
                'verbose_name': 'Недельный отчёт',
                'verbose_name_plural': 'Недельные отчёты',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('period_type', models.CharField(choices=[('week', 'Неделя'), ('month', 'Месяц')], max_length=10, verbose_name='Период')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('data', models.JSONField(default=dict, verbose_name='KPI')),
            ],
            options={
                'verbose_name': 'KPI snapshot',
                'verbose_name_plural': 'KPI snapshots',
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_start')},
            },
        ),
    ]
