# Generated by Django 5.2 on 2026-08-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('month_start', models.DateField(unique=True, verbose_name='Месяц')),
                ('data', models.JSONField(default=dict, verbose_name='Показатели')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий руководителя')),
            ],
            options={
                'verbose_name': 'Месячный отчёт',
                'verbose_name_plural': 'Месячные отчёты',
                'ordering': ['-month_start'],
            },
        ),
    ]
