# Generated by Django 5.2 on 2026-08-14 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interns', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('role', models.CharField(choices=[('pm', 'Project Manager'), ('team_lead', 'Team Lead'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('mobile', 'Mobile'), ('uxui', 'UX/UI'), ('qa', 'QA'), ('other', 'Other')], max_length=20, verbose_name='Роль')),
                ('joined_at', models.DateField(blank=True, null=True, verbose_name='Дата подключения')),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('workload', models.PositiveSmallIntegerField(default=50, verbose_name='Загрузка, %')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('left', 'Вышел')], db_index=True, default='active', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('intern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='interns.intern', verbose_name='Стажёр')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project', verbose_name='Проект')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команд',
                'ordering': ['role'],
            },
        ),
    ]
