# Generated by Django 5.2 on 2026-08-15 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_group'),
        ('projects', '0010_flow_relation'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='flows.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project', verbose_name='Проект'),
        ),
    ]
