# Generated by Django 5.2 on 2026-09-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammember_group_alter_teammember_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='left_reason',
            field=models.CharField(blank=True, choices=[('self', 'Сам ушёл'), ('unresponsive', 'Не отвечает'), ('not_fit', 'Не подошёл'), ('project_ended', 'Проект завершён'), ('other', 'Другое')], max_length=20, verbose_name='Причина выхода'),
        ),
    ]
