# Generated by Django 5.2 on 2026-08-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('potential', 'Потенциальный'), ('negotiation', 'Переговоры'), ('awaiting_docs', 'Ожидаем документы'), ('confirmed', 'Подтверждён'), ('team_forming', 'Формирование команды'), ('launched', 'Запущен'), ('rejected', 'Отказ')], db_index=True, default='potential', max_length=20, verbose_name='Статус')),
                ('probability', models.PositiveSmallIntegerField(default=50, verbose_name='Вероятность запуска, %')),
                ('expected_start', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата старта')),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность, мес.')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projecttype', verbose_name='Тип проекта')),
            ],
            options={
                'verbose_name': 'Планируемый проект',
                'verbose_name_plural': 'Планируемые проекты',
                'ordering': ['expected_start'],
            },
        ),
        migrations.CreateModel(
            name='PlannedProjectNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Человек')),
                ('planned_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='resources.plannedproject', verbose_name='Планируемый проект')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='training.specialization', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Потребность планируемого проекта',
                'verbose_name_plural': 'Потребности планируемых проектов',
                'unique_together': {('planned_project', 'specialization')},
            },
        ),
    ]
