# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_report_single_text'),
        ('training', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Сколько человек')),
                ('needed_by', models.DateField(blank=True, null=True, verbose_name='Нужны к дате')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто запросил')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_requests', to='projects.project', verbose_name='Проект')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='training.specialization', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Запрос на стажёров',
                'verbose_name_plural': 'Запросы на стажёров',
                'ordering': ['is_closed', 'needed_by'],
            },
        ),
    ]
