# Generated by Django 5.2 on 2026-08-14 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('meeting_type', models.CharField(choices=[('pm_weekly', 'PM Weekly'), ('team_lead', 'Team Lead Meeting'), ('project', 'Project Meeting'), ('kickoff', 'Kickoff'), ('client', 'Client Meeting'), ('delivery', 'Delivery Meeting'), ('internal', 'Internal'), ('other', 'Other')], default='internal', max_length=20, verbose_name='Тип')),
                ('external_participants', models.CharField(blank=True, help_text='Например, представители клиента', max_length=255, verbose_name='Внешние участники')),
                ('agenda', models.TextField(blank=True, verbose_name='Повестка')),
                ('discussion', models.TextField(blank=True, verbose_name='Обсуждение')),
                ('next_meeting_date', models.DateField(blank=True, null=True, verbose_name='Следующее собрание')),
                ('participants', models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Собрание',
                'verbose_name_plural': 'Собрания',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('text', models.TextField(verbose_name='Решение')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('done', 'Выполнено'), ('cancelled', 'Отменено')], default='open', max_length=10, verbose_name='Статус')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='meetings.meeting', verbose_name='Собрание')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Решение собрания',
                'verbose_name_plural': 'Решения собраний',
                'ordering': ['created_at'],
            },
        ),
    ]
