# Generated by Django 5.2 on 2026-08-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0003_fill_groups'),
        ('interns', '0002_intern_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('kind', models.CharField(choices=[('pm_interns', 'PM со стажёрами'), ('lead_interns', 'Тимлид со стажёрами'), ('internal', 'Внутреннее (PM и тимлиды)'), ('other', 'Другое')], default='pm_interns', max_length=20, verbose_name='Вид собрания')),
                ('times_per_week', models.PositiveSmallIntegerField(default=1, verbose_name='Раз в неделю')),
                ('weekdays', models.CharField(blank=True, help_text='Номера дней через запятую: 0 — понедельник, 6 — воскресенье', max_length=20, verbose_name='Дни недели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_plans', to='flows.group', verbose_name='Группа')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_plans', to='interns.intern', verbose_name='Кто проводит')),
            ],
            options={
                'verbose_name': 'План собраний',
                'verbose_name_plural': 'Планы собраний',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='GroupMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('kind', models.CharField(choices=[('pm_interns', 'PM со стажёрами'), ('lead_interns', 'Тимлид со стажёрами'), ('internal', 'Внутреннее (PM и тимлиды)'), ('other', 'Другое')], default='pm_interns', max_length=20, verbose_name='Вид')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('held', 'Проведено'), ('missed', 'Не проведено')], db_index=True, default='planned', max_length=10, verbose_name='Статус')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='flows.group', verbose_name='Группа')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_meetings', to='interns.intern', verbose_name='Провёл')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='attendance.meetingplan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Собрание группы',
                'verbose_name_plural': 'Собрания групп',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('status', models.CharField(choices=[('present', 'Был'), ('absent', 'Не был'), ('late', 'Опоздал'), ('excused', 'Уважительная')], default='present', max_length=10, verbose_name='Отметка')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='interns.intern', verbose_name='Человек')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отметил')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance.groupmeeting', verbose_name='Собрание')),
            ],
            options={
                'verbose_name': 'Отметка посещения',
                'verbose_name_plural': 'Табель посещаемости',
                'unique_together': {('meeting', 'intern')},
            },
        ),
        migrations.AddIndex(
            model_name='groupmeeting',
            index=models.Index(fields=['group', 'date'], name='attendance__group_i_2c08d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmeeting',
            unique_together={('group', 'kind', 'date')},
        ),
    ]
