# Generated by Django 5.2 on 2026-08-16 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0003_fill_groups'),
        ('interns', '0002_intern_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('present', 'Был'), ('absent', 'Не был'), ('late', 'Опоздал'), ('excused', 'Уважительная')], default='present', max_length=10, verbose_name='Отметка')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='flows.group', verbose_name='Группа')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='interns.intern', verbose_name='Человек')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отметил')),
            ],
            options={
                'verbose_name': 'Отметка табеля',
                'verbose_name_plural': 'Табель',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['group', 'date'], name='attendance__group_i_95d31e_idx')],
                'unique_together': {('group', 'intern', 'date')},
            },
        ),
    ]
