# Generated by Django 5.2 on 2026-08-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmeeting',
            name='plan',
        ),
        migrations.DeleteModel(
            name='MeetingPlan',
        ),
    ]
