# Generated by Django 5.2 on 2026-08-19 07:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_groupmeeting_plan_delete_meetingplan'),
        ('interns', '0002_intern_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Балл')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_scores', to='interns.intern', verbose_name='Человек')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Оценил')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='attendance.groupmeeting', verbose_name='Собрание')),
            ],
            options={
                'verbose_name': 'Оценка работы',
                'verbose_name_plural': 'Оценки работы',
                'unique_together': {('meeting', 'intern')},
            },
        ),
    ]
