# Generated by Django 5.2 on 2026-10-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_workscore'),
        ('flows', '0003_fill_groups'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmeeting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='groupmeeting',
            name='direction',
            field=models.CharField(blank=True, db_index=True, help_text='Роль в команде, для которой собрание: тимлид собирает только своё направление. Пусто — общее собрание команды.', max_length=20, verbose_name='Направление'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmeeting',
            unique_together={('group', 'kind', 'date', 'direction')},
        ),
    ]
