# Generated by Django 5.2 on 2026-08-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип проекта',
                'verbose_name_plural': 'Типы проектов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Внутренний ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Город / филиал')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата подписания договора')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('planned_end_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Плановая дата завершения')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата завершения')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('paused', 'Приостановлен'), ('cancelled', 'Отменён'), ('refused', 'Клиент отказался'), ('completed', 'Завершён')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('current_stage', models.CharField(choices=[('new', 'Новый'), ('documents', 'Документы'), ('requirements', 'ТЗ'), ('team_forming', 'Формирование команды'), ('design', 'Дизайн'), ('development', 'Разработка'), ('testing', 'Тестирование'), ('rework', 'Доработка'), ('production', 'Продакшен'), ('delivery', 'Сдача'), ('completed', 'Завершён')], db_index=True, default='new', max_length=20, verbose_name='Текущий этап')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Процент готовности')),
                ('head_comment', models.TextField(blank=True, verbose_name='Комментарий руководителя')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('figma_url', models.URLField(blank=True, verbose_name='Figma')),
                ('staging_url', models.URLField(blank=True, verbose_name='Staging URL')),
                ('production_url', models.URLField(blank=True, verbose_name='Production URL')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Домен')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранный')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client', verbose_name='Заказчик')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Team Lead')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projecttype', verbose_name='Тип проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Ссылка проекта',
                'verbose_name_plural': 'Ссылки проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('field', models.CharField(max_length=50, verbose_name='Поле')),
                ('old_value', models.CharField(blank=True, max_length=255, verbose_name='Старое значение')),
                ('new_value', models.CharField(blank=True, max_length=255, verbose_name='Новое значение')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.project', verbose_name='Проект')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История проекта',
                'verbose_name_plural': 'История проектов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('key', models.CharField(choices=[('new', 'Новый'), ('documents', 'Документы'), ('requirements', 'ТЗ'), ('team_forming', 'Формирование команды'), ('design', 'Дизайн'), ('development', 'Разработка'), ('testing', 'Тестирование'), ('rework', 'Доработка'), ('production', 'Продакшен'), ('delivery', 'Сдача'), ('completed', 'Завершён')], max_length=20, verbose_name='Этап')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Завершено'), ('blocked', 'Заблокировано')], db_index=True, default='not_started', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('deadline', models.DateField(blank=True, db_index=True, null=True, verbose_name='Deadline')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='Проект')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_stages', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Этап проекта',
                'verbose_name_plural': 'Этапы проектов',
                'ordering': ['order'],
                'unique_together': {('project', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'current_stage'], name='projects_pr_status_21b1a2_idx'),
        ),
    ]
