# Generated by Django 5.2 on 2026-08-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flow',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Поток'),
        ),
    ]
