# Generated by Django 5.2 on 2026-08-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_backfill_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('service', models.CharField(help_text='Например: Админка сайта, Хостинг, База данных, Домен', max_length=100, verbose_name='Сервис')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Адрес / URL')),
                ('login', models.CharField(blank=True, max_length=255, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Пароль')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Доступ проекта',
                'verbose_name_plural': 'Доступы проектов',
                'ordering': ['service'],
            },
        ),
    ]
