# Generated by Django 5.2 on 2026-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_stage',
            field=models.CharField(choices=[('new', 'Новый'), ('documents', 'Документы'), ('requirements', 'ТЗ'), ('team_forming', 'Формирование команды'), ('design', 'Дизайн'), ('development', 'Разработка'), ('staging', 'Тестовый сервер'), ('testing', 'Тестирование'), ('rework', 'Доработка'), ('delivery', 'Сдача'), ('production', 'Продакшен'), ('completed', 'Завершён')], db_index=True, default='new', max_length=20, verbose_name='Текущий этап'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='key',
            field=models.CharField(choices=[('new', 'Новый'), ('documents', 'Документы'), ('requirements', 'ТЗ'), ('team_forming', 'Формирование команды'), ('design', 'Дизайн'), ('development', 'Разработка'), ('staging', 'Тестовый сервер'), ('testing', 'Тестирование'), ('rework', 'Доработка'), ('delivery', 'Сдача'), ('production', 'Продакшен'), ('completed', 'Завершён')], max_length=20, verbose_name='Этап'),
        ),
    ]
