# Generated by Django 5.2 on 2026-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_collapse_stage_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('done', 'Завершён')], db_index=True, default='not_started', max_length=20, verbose_name='Статус'),
        ),
    ]
