# Generated by Django 5.2 on 2026-08-19 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_intern_flow'),
        ('projects', '0010_flow_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('service', models.CharField(max_length=100, verbose_name='Что нужно')),
                ('comment', models.TextField(blank=True, verbose_name='Зачем / уточнение')),
                ('status', models.CharField(choices=[('pending', 'Ждём от ПМ'), ('provided', 'Выдан'), ('declined', 'Отказано')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('answer', models.CharField(blank=True, max_length=255, verbose_name='Ответ ПМ')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт')),
                ('access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='projects.projectaccess', verbose_name='Выданный доступ')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='interns.intern', verbose_name='У кого запросили')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='projects.project', verbose_name='Проект')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
            ],
            options={
                'verbose_name': 'Запрос доступа',
                'verbose_name_plural': 'Запросы доступа',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
