# Generated by Django 5.2 on 2026-08-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_flow_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_lead',
        ),
    ]
