# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_report_single_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_problematic',
            field=models.BooleanField(default=False, verbose_name='Проблемный'),
        ),
    ]
