# Generated by Django 5.2 on 2026-09-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_is_problematic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stages_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ПМ сверил этапы'),
        ),
    ]
