# Generated by Django 5.2 on 2026-09-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_stages_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frontend_repo_url',
            field=models.URLField(blank=True, verbose_name='Репозиторий фронтенда'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='Репозиторий бэкенда'),
        ),
    ]
