# Generated by Django 5.2 on 2026-08-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер потока')),
                ('status', models.CharField(choices=[('planned', 'Набор'), ('active', 'Активный'), ('finished', 'Завершён')], db_index=True, default='active', max_length=10, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало стажировки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание стажировки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
                'ordering': ['-number'],
            },
        ),
    ]
