# Generated by Django 5.2 on 2026-08-15 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
        ('projects', '0010_flow_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер группы')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='flows.flow', verbose_name='Поток')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['flow__number', 'number'],
                'unique_together': {('flow', 'number')},
            },
        ),
    ]
