# Generated by Django 5.2 on 2026-08-14 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='Филиал')),
                ('education_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('internship_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала стажировки')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает стажировки'), ('ready', 'Готов к распределению'), ('internship', 'На стажировке'), ('active', 'Активный'), ('paused', 'Приостановлен'), ('employable', 'Готов к трудоустройству'), ('employed', 'Трудоустроен'), ('dropped', 'Выбыл')], db_index=True, default='waiting', max_length=20, verbose_name='Статус')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interns', to='training.specialization', verbose_name='Направление')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_interns', to=settings.AUTH_USER_MODEL, verbose_name='Текущий Team Lead')),
                ('training_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interns', to='training.traininggroup', verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name': 'Стажёр',
                'verbose_name_plural': 'Стажёры',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='InternEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('hard_skills', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Hard skills')),
                ('quality', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Качество работы')),
                ('speed', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Скорость')),
                ('responsibility', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Ответственность')),
                ('communication', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Коммуникация')),
                ('teamwork', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Teamwork')),
                ('independence', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Самостоятельность')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Оценил')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interns.intern', verbose_name='Стажёр')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Оценка стажёра',
                'verbose_name_plural': 'Оценки стажёров',
                'ordering': ['-created_at'],
            },
        ),
    ]
