# Generated by Django 5.2 on 2026-08-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interns', to='flows.flow', verbose_name='Поток'),
        ),
    ]
