# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_intern_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
    ]
