# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interns', '0003_intern_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intern_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись'),
        ),
    ]
