# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0004_intern_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='in_resume_bank',
            field=models.BooleanField(default=False, verbose_name='В банке резюме'),
        ),
        migrations.AddField(
            model_name='intern',
            name='in_talent_reserve',
            field=models.BooleanField(default=False, verbose_name='В резерве кадров'),
        ),
    ]
