# Generated by Django 5.2

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0005_intern_reserve_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='internship_attempt',
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Какая по счёту стажировка',
            ),
        ),
    ]
