# Generated by Django 5.2

from django.db import migrations, models


def normalize_branch(apps, schema_editor):
    Intern = apps.get_model('interns', 'Intern')
    Intern.objects.filter(branch='Бишкекский филиал').update(branch='Бишкек')


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0006_intern_internship_attempt'),
    ]

    operations = [
        migrations.RunPython(normalize_branch, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='intern',
            name='branch',
            field=models.CharField(
                blank=True,
                choices=[('Бишкек', 'Бишкек'), ('Ош', 'Ош')],
                max_length=20,
                verbose_name='Филиал',
            ),
        ),
    ]
