# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        ('interns', '0007_intern_branch_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='in_talent_reserve',
        ),
        migrations.CreateModel(
            name='TalentReserveCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('desired_role', models.CharField(blank=True, max_length=255, verbose_name='Желаемая роль/позиция')),
                ('experience', models.TextField(blank=True, verbose_name='О себе / опыт')),
                ('portfolio_link', models.URLField(blank=True, verbose_name='Портфолио / резюме — ссылка')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Чем больше число, тем выше в списке.', verbose_name='Приоритет')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserve_candidates', to='training.specialization', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Кандидат в резерве',
                'verbose_name_plural': 'Резерв кадров',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
