# Generated by Django 5.2 on 2026-09-09 12:52

import apps.interns.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0008_talent_reserve_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('token', models.CharField(default=apps.interns.models.generate_form_token, max_length=64, unique=True, verbose_name='Токен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('submissions', models.PositiveIntegerField(default=0, verbose_name='Заполнений')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Отключена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Ссылка на анкету стажёра',
                'verbose_name_plural': 'Ссылки на анкету стажёра',
                'ordering': ['-created_at'],
            },
        ),
    ]
