# Generated by Django 5.2 on 2026-09-09 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0009_profileformlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileformlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Пусто — ссылка живёт, пока её не заменят или не отключат.', null=True, verbose_name='Действует до'),
        ),
        migrations.CreateModel(
            name='ProfileFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новая карточка')),
                ('intern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='interns.intern', verbose_name='Стажёр')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_log', to='interns.profileformlink', verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Заполнение анкеты',
                'verbose_name_plural': 'Заполнения анкеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
