# Generated by Django 5.2

from django.db import migrations, models


def merge_internship_into_active(apps, schema_editor):
    Intern = apps.get_model('interns', 'Intern')
    Intern.objects.filter(status='internship').update(status='active')


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0010_profileformlink_expires_at_profileformsubmission'),
    ]

    operations = [
        migrations.RunPython(merge_internship_into_active, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='intern',
            name='status',
            field=models.CharField(
                choices=[
                    ('waiting', 'Ожидает стажировки'),
                    ('ready', 'Готов к распределению'),
                    ('active', 'Активный'),
                    ('paused', 'Приостановлен'),
                    ('employable', 'Готов к трудоустройству'),
                    ('employed', 'Трудоустроен'),
                    ('dropped', 'Выбыл'),
                ],
                db_index=True,
                default='waiting',
                max_length=20,
                verbose_name='Статус',
            ),
        ),
    ]
