# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0011_merge_internship_status_into_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='graduate_status',
            field=models.CharField(
                blank=True,
                choices=[('pending', 'На проверке'), ('declined', 'Не хочет продолжать')],
                max_length=10,
                verbose_name='Статус выпускника',
            ),
        ),
    ]
