# Generated by Django 5.2 on 2026-09-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0012_intern_graduate_status'),
        ('projects', '0015_project_stages_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileformlink',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Кто заполнит анкету по этой ссылке — сразу в команду проекта.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to='projects.project', verbose_name='Проект'),
        ),
    ]
