# Generated by Django 5.2 on 2026-09-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0013_profileformlink_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='resume_bank_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий по доработке (банк резюме)'),
        ),
        migrations.AddField(
            model_name='intern',
            name='resume_bank_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает проверки'), ('approved', 'Принят'), ('revision', 'На доработке')], max_length=10, verbose_name='Статус банка резюме'),
        ),
        migrations.AddField(
            model_name='intern',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram chat id'),
        ),
    ]
