# Generated by Django 5.2 on 2026-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0014_intern_resume_bank_comment_intern_resume_bank_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='phone_lock_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Бот-выпускник: блокировка проверки телефона до'),
        ),
    ]
