# Generated by Django 5.2 on 2026-09-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0015_intern_phone_lock_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='graduate_status',
            field=models.CharField(blank=True, choices=[('pending', 'На проверке'), ('declined', 'Не хочет продолжать'), ('waiting', 'Ждёт проект')], max_length=10, verbose_name='Статус выпускника'),
        ),
    ]
