# Generated by Django 5.2 on 2026-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0016_alter_intern_graduate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='rules_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Бот-выпускник: ознакомлен с правилами'),
        ),
    ]
