# Generated by Django 5.2 on 2026-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0017_intern_rules_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='position',
            field=models.CharField(choices=[('intern', 'Стажёр'), ('lead', 'Тимлид'), ('pm', 'Проект-менеджер')], db_index=True, default='intern', help_text='Тимлид остаётся тимлидом на всех проектах, пока его не снимут.', max_length=10, verbose_name='Должность'),
        ),
    ]
