# Generated by Django 5.2 on 2026-10-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0018_intern_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='bot_reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Бот-выпускник: последнее напоминание'),
        ),
    ]
