# Generated by Django 5.2 on 2026-09-12 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(blank=True, help_text='Например: Стажёрам, Клиентам, Вакансии. Можно оставить пустым.', max_length=100, verbose_name='Категория')),
                ('body', models.TextField(verbose_name='Текст')),
                ('is_pinned', models.BooleanField(default=False, help_text='Часто используемые — наверх списка.', verbose_name='Закрепить сверху')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Скрипт',
                'verbose_name_plural': 'Скрипты',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
    ]
