# Generated by Django 5.2 on 2026-08-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('number', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='Филиал')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата окончания')),
                ('students_count', models.PositiveSmallIntegerField(default=0, verbose_name='Обучающихся')),
                ('expected_interns', models.PositiveSmallIntegerField(default=0, verbose_name='Прогноз перехода в стажировку')),
                ('actual_interns', models.PositiveSmallIntegerField(default=0, verbose_name='Фактически пришло')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='training.specialization', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['end_date'],
            },
        ),
    ]
