# Generated by Django 5.2 on 2026-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='status',
            field=models.CharField(choices=[('recruiting', 'Набор'), ('studying', 'Учится'), ('graduated', 'Выпущена'), ('cancelled', 'Не состоялась')], db_index=True, default='studying', max_length=12, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='teacher',
            field=models.CharField(blank=True, max_length=255, verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='wants_internship',
            field=models.PositiveSmallIntegerField(default=0, help_text='Сколько студентов сами сказали, что пойдут на стажировку.', verbose_name='Хотят на стажировку'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='expected_interns',
            field=models.PositiveSmallIntegerField(default=0, help_text='Наша оценка: сколько реально дойдёт.', verbose_name='Прогноз перехода в стажировку'),
        ),
    ]
