# Generated by Django 5.2 on 2026-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_traininggroup_comment_traininggroup_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='students_note',
            field=models.CharField(blank=True, help_text='Как прислали: «5–7», «на старте» и т.п.', max_length=100, verbose_name='Уточнение по студентам'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='status',
            field=models.CharField(choices=[('recruiting', 'Набор'), ('studying', 'Учится'), ('graduated', 'Выпущена'), ('cancelled', 'Не состоялась')], db_index=True, default='studying', help_text='Ставится сам по датам; вручную — только «Не состоялась».', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='students_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Пусто — академия ещё не сообщила.', null=True, verbose_name='Обучающихся'),
        ),
    ]
