# Generated by Django 5.2 on 2026-09-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_traininggroup_students_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggroup',
            name='branch',
            field=models.CharField(blank=True, choices=[('Бишкек', 'Бишкек'), ('Ош', 'Ош')], db_index=True, help_text='Бишкек и Ош набирают группы независимо, номера могут совпадать.', max_length=100, verbose_name='Филиал'),
        ),
    ]
