# Generated by Django 5.2 on 2026-08-19 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=200, verbose_name='Пункт')),
                ('hint', models.CharField(blank=True, max_length=255, verbose_name='Пояснение')),
                ('block', models.CharField(choices=[('projects', 'Проекты'), ('people', 'Люди и команды'), ('meetings', 'Собрания и табель'), ('office', 'Офис и организация')], db_index=True, default='projects', max_length=20, verbose_name='Блок')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Пункт проверки',
                'verbose_name_plural': 'Пункты ежедневной проверки',
                'ordering': ['block', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CheckMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('is_done', models.BooleanField(default=True, verbose_name='Проверено')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Что заметил')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='dailycheck.checkitem', verbose_name='Пункт')),
            ],
            options={
                'verbose_name': 'Отметка проверки',
                'verbose_name_plural': 'Отметки ежедневной проверки',
                'ordering': ['-date'],
                'unique_together': {('date', 'item')},
            },
        ),
    ]
