# Generated by Django 5.2 on 2026-08-19 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycheck', '0001_initial'),
        ('projects', '0010_flow_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=200, verbose_name='Пункт')),
                ('hint', models.CharField(blank=True, max_length=255, verbose_name='Пояснение')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_items', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Ежедневный пункт проекта',
                'verbose_name_plural': 'Ежедневные пункты проектов',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCheckMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('is_done', models.BooleanField(default=True, verbose_name='Проверено')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Что заметил')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='dailycheck.projectcheckitem', verbose_name='Пункт')),
            ],
            options={
                'verbose_name': 'Отметка по проекту',
                'verbose_name_plural': 'Ежедневные отметки по проектам',
                'ordering': ['-date'],
                'unique_together': {('date', 'item')},
            },
        ),
    ]
